services:
  app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - FLASK_APP=run.py  # <-- Update to `run.py`
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"