version: '3.8'

services:
  flask:
    build: .
    container_name: flask_bot
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - TELEGRAM_BOT_TOKEN=your_bot_token

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info